# =============================================================================
# SonarQube Configuration
# =============================================================================
# Scan tự động khi tích hợp Jenkins: mvn sonar:sonar
# Scan thủ công: sonar-scanner (chạy 1 lần)
# =============================================================================

sonar.projectKey=demo-app
sonar.projectName=Demo App (DevOps Training)
sonar.projectVersion=1.0

# Source code
sonar.sources=src/
# sonar.java.binaries=src/02-backend_spring-boot-rest-api/target/   # Cần build trước
sonar.language=java
sonar.sourceEncoding=UTF-8

# Exclude test & node_modules
sonar.exclusions=src/03-frontend_angular-ecommerce/node_modules/**,**/*.spec.ts
