# =============================================================================
# ArgoCD Application – demo-app (DEV)
# Được tạo tự động bởi dev-root (App-of-Apps)
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/lehoangtien2510/devops-training-lehoangtien
    targetRevision: Week-5-CICD
    path: charts/demo-app

    helm:
      valueFiles:
        - values.yaml
      values: |
        backend:
          image:
            tag: latest
        frontend:
          image:
            tag: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
